### ISSUE TITLE
Recipe schema validation function does not handle non-string values

### ISSUE THREAD

**Issue by schuylermartin45** [anaconda-distribution/percy#35]
It looks like I can't change non-string values in a recipe because the JSON validator is too strict.

I'm trying to set an integer in `recipe-bootstrapper` but I think we also want support for boolean values as well.

```
Traceback (most recent call last):
  File "/Users/smartin/anaconda_3/anaconda3/envs/perseverance-scripts/bin/pscripts", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/Users/smartin/anaconda_3/anaconda3/envs/perseverance-scripts/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/smartin/anaconda_3/anaconda3/envs/perseverance-scripts/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/smartin/anaconda_3/anaconda3/envs/perseverance-scripts/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/smartin/anaconda_3/anaconda3/envs/perseverance-scripts/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/smartin/anaconda_3/anaconda3/envs/perseverance-scripts/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/smartin/work/perseverance-scripts/perseverance_scripts/commands/recipe_bootstrapper.py", line 134, in recipe_bootstrapper
    recipe_reset_build_number(recipe)  # type: ignore[misc]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/smartin/work/perseverance-scripts/perseverance_scripts/commands/recipe_bootstrapper.py", line 30, in recipe_reset_build_number
    recipe.patch(  # type: ignore[misc]
  File "/Users/smartin/anaconda_3/anaconda3/envs/perseverance-scripts/lib/python3.11/site-packages/percy/render/recipe.py", line 638, in patch
    jsonschema.validate(operations, self.schema)
  File "/Users/smartin/anaconda_3/anaconda3/envs/perseverance-scripts/lib/python3.11/site-packages/jsonschema/validators.py", line 1307, in validate
    raise error
jsonschema.exceptions.ValidationError: 0 is not of type 'string', 'array'

Failed validating 'type' in schema['items']['properties']['value']:
    {'items': {'type': 'string'}, 'type': ['string', 'array']}
```

**Comment by schuylermartin45** [comment]
The `PERCY` parser bypasses this check and performs it's own validation on the patch, which handles non string types.

Closing.
